name: credit-card-approval
channels:
  - conda-forge
dependencies:
  - python=3.10

  # Core Repository
  - numpy
  - pandas

  # Visualization and EDA
  - matplotlib
  - seaborn
  - missingno

  # Machine Learning
  - scikit-learn
  - lightgbm

  # Parquet IO
  - pyarrow

  # Notebook support
  - notebook
  - ipykernel

  # Testing
  - pytest
  - pytest-cov

  # Others
  - pip
  - pip:
      - pre-commit