[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "credit-card-approval-project"
version = "0.1.0"
description = "Credit card approval prediction using GLM and LightGBM"
readme = "README.md"
requires-python = ">=3.9"

authors = [
    { name = "6142P", email = "nc681@cam.ac.uk" }
]

dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "lightgbm",
    "matplotlib",
    "seaborn",
    "joblib",
]


[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
